# Multilingual Antonym Detection Training Configuration

datasets:
  base_dir: "/home/samyak/scratch/temp/multilingual_antonym_detection/datasets"
  languages:
    - german
    - french
    - spanish
    - italian
    - portuguese
    - dutch
    - russian
    - english

models:
  bert_dir: "/home/samyak/scratch/temp/multilingual_antonym_detection/models/bert"
  output_dir: "/home/samyak/scratch/temp/multilingual_antonym_detection/models/trained"
  model_types:
    - bert
    - dual_encoder

training:
  batch_size: 16
  learning_rate: 2e-5
  epochs: 3
  max_length: 128
  warmup_steps: 100
  weight_decay: 0.01
  
  # Data splits (if not using pre-split data)
  test_size: 0.2
  val_size: 0.1

hardware:
  use_gpu: true
  mixed_precision: true
  
evaluation:
  save_plots: true
  save_confusion_matrix: true
  save_metrics: true

# Language-specific overrides
language_overrides:
  russian:
    # Russian might need different parameters
    learning_rate: 1e-5
    epochs: 4
  
  german:
    # German has most data
    batch_size: 32
